= Bz Kanban Board

== About

Visualize Bugzilla milestones as cards and columns with a Kanban inspired board.

The goal is to compliment an existing Bugzilla workflow, so board columns represent actual bug statuses.
Cards can be dragged from one column to another to change the bug status.

It is implemented as a single-page application using Ajax with the http://bugzilla.readthedocs.io/en/latest/api/index.html[Bugzilla 5 server REST API].

== Demo

https://rawgit.com/leif81/bzkanban/master/index.html?product=Bugzilla&milestone=Bugzilla+6.0&assignee=&comments=false&site=https%3A%2F%2Fbugzilla.mozilla.org[Try it].

== Requirements

 . Client: A modern web browser capable of HTML5, CSS3, and JavaScript.
 . Server: A Bugzilla 5.0+ server with REST API enabled.

== Installation

 . Clone this git repo.
 . Configure which Bugzilla instance to connect to by modifying the hardcoded `bzSiteUrl` value in the `bzkanban.js` code.

== Usage

 . Open the `index.html` in your web browser.
 . Pick a product and milestone and view the board!
 . Log in to enable editing cards, which includes dragging cards between columns.

=== Advanced

These are some settings that can be manually controlled via the page URL.

 * `site`
 ** The Bugzilla instance to load data from. Overrides the internal `bzSiteUrl` setting. e.g. `site=https://bugzilla.mozilla.org`
 * `comments`
 ** Show comment counts on cards. WARNING: it's expensive, one more request per card. e.g. `comments=true/false`
 * `autorefresh`
 ** Reload the board when external changes to bugs are detected. e.g. `autorefresh=true/false`
