= Bz Kanban Board

== About

Visualize Bugzilla milestones as cards and columns with a Kanban inspired board.

The goal is to compliment an existing Bugzilla workflow, so board columns represent actual bug statuses.
Cards can be dragged from one column to another to change the bug status.

== Demo

https://rawgit.com/leif81/bzkanban/master/index.html?product=Bugzilla&milestone=Bugzilla+6.0&assignee=&comments=false&site=https%3A%2F%2Fbugzilla.mozilla.org[Try it].

== Requirements

 . Client: A modern web browser capable of HTML5, CSS3, and JavaScript.
 . Server: A Bugzilla instance running v5.0 or higher (because the board uses the awesome new http://bugzilla.readthedocs.io/en/latest/api/index.html[Bugzilla REST API]).

== Installation

 . Clone this git repo.
 . Configure which Bugzilla instance to connect to by modifying the hardcoded `bzSiteUrl` value in the `bzkanban.js` code.

== Usage

 . Open the `index.html` in your web brower.
 . Pick a product and milestone and view the board!

=== Advanced

These are some settings that can be manually controlled via the page URL.

 * `site`
 ** The Bugzilla instance to load data from. Overrides the internal setting. e.g. `site=https://bugzilla.mozilla.org`
 * `comments`
 ** Show comment counts on cards. WARNING: it's expensive, one more request per card. e.g. `comments=true/false`
 * `autocomments`
 ** Add a comment when making changes to bugs. e.g. `autocomment=true/false`
 * `autorefresh`
 ** Reload the board when external changes to bugs are detected. e.g. `autorefresh=true/false`
 * `gravatar`
 ** Show user gravatar images. e.g. `gravatar=true/false`
