= Bz Kanban Board

== About

This allows you to visualize your Bugzilla product milestones with a Kanban inspired board.

The goal is to compliment an existing Bugzilla workflow, so the board columns represent the bug statuses and the cards represent the bugs.
Cards can be opened to view comments or add a new comment.
Cards can be dragged from one column to another to change the bug status.

It is implemented as a single-page application using Ajax with the http://bugzilla.readthedocs.io/en/latest/api/index.html[Bugzilla 5 server REST API].

== Demo

https://rawgit.com/leif81/bzkanban/master/index.html?product=Bugzilla&milestone=Bugzilla+6.0&assignee=&comments=false&site=https%3A%2F%2Fbugzilla.mozilla.org[Try it].

== Requirements

 . Client: A modern web browser capable of HTML5, CSS3, and JavaScript (tested with Chrome and Edge)
 . Server: A Bugzilla 5.0+ server with REST API enabled.

== Installation

 . Clone this git repo.
 . Configure which Bugzilla instance to connect to by modifying the hardcoded `bzSiteUrl` value in the `bzkanban.js` code.

== Usage

 . Open the `index.html` in your web browser.
 . Pick a product and milestone and view the board!
 . Log in to enable editing cards, which includes dragging cards between columns.

=== Advanced

These are some settings that can be manually controlled via the page URL.

 * `site`
 ** The Bugzilla instance to load data from. Overrides the internal `bzSiteUrl` setting. e.g. `site=https://bugzilla.mozilla.org`
 * `comments`
 ** Show comment counts on cards. WARNING: it's expensive, one more request per card. e.g. `comments=true/false`
 * `autorefresh`
 ** Reload the board when external changes to bugs are detected. e.g. `autorefresh=true/false`
