= Bz Kanban Board

== About

Visualize Bugzilla milestones as cards and columns with a Kanban inspired board.

The goal is to compliment an existing Bugzilla workflow, so board columns represent actual bug statuses.
And bug updates (commenting, changing status, etc) require using the existing Bugzilla interface.

== Demo

https://rawgit.com/leif81/bzkanban/master/index.html?product=Bugzilla&milestone=Bugzilla+6.0&assignee=&comments=false&site=https%3A%2F%2Fbugzilla.mozilla.org[Try it].

== Requirements

 . Client: A modern web browser capable of HTML5, CSS3, and JavaScript.
 . Server: An existing Bugzilla 5.0+ server (because the board uses the awesome new http://bugzilla.readthedocs.io/en/latest/api/index.html[Bugzilla REST API]).

== Installation

 . Clone this git repo.
 . Configure which Bugzilla instance to connect to by modifying the hardcoded `bzSiteUrl` value in the `index.html` code.

== Usage

 . Open the `index.html` in your web brower.
 . Pick a product and milestone and view the board!

=== Advanced

These are optional settings that can be manually added to the page URL to control the board.

 * `site`
 ** Override the internal Bugzilla instance URL to load from. e.g. `site=https://bugzilla.mozilla.org`
 * `comments`
 ** Show comment counts on cards. WARNING: it's expensive, one more request per card. e.g. `comments=true`
 * `autocomments`
 ** Enable auto comments when making changes to bugs. e.g. `autocomment=true`
 * `autorefresh`
 ** Enable auto refresh when changes are detected. e.g. `autorefresh=true`
 * `gravatar`
 ** Disable use of an external avatar site. e.g. `gravatar=false`
